name: Airstrike
main: airstrike.Airstrike
version: 1.2
authors: [muCkk, zhuowei]
commands:
  as:
    description: bomb players with TNT or creepers
    usage: |
             /as <tnt/cr> <player> <amount> <height>
  asset:
      description: Used to set up the config
      usage: |
              /asset <key> <value>
